Thu Dec 16 10:55:17 UTC 2021
Loading Dataset !
Loading Abs_Pos Bert SigHan Dataset ...
[Errno 2] No such file or directory: '/data/rawdata/sighan/lattice/train.src'
Traceback (most recent call last):
  File "bert_MaskedLM_v2.py", line 307, in <module>
    run()
  File "bert_MaskedLM_v2.py", line 212, in run
    train_dataset, eval_dataset, test_dataset = get_magic_dataset(training_args.dataset) 
  File "/remote-home/xtzhang/CTC/CTC2021/SpecialEdition/core.py", line 111, in get_magic_dataset
    train_data, eval_data, test_data = load_abs_pos_sighan(path_head=path_head)
  File "/remote-home/xtzhang/anaconda3/envs/115/lib/python3.8/site-packages/fastNLP/core/utils.py", line 357, in wrapper
    results = func(*args, **kwargs)
  File "/remote-home/xtzhang/CTC/CTC2021/SpecialEdition/data/DatasetLoadingHelper.py", line 460, in load_abs_pos_sighan
    train_pkg, valid_pkg, test_pkg = load_raw_lattice(path_head=path_head) 
  File "/remote-home/xtzhang/CTC/CTC2021/SpecialEdition/data/DatasetLoadingHelper.py", line 232, in load_raw_lattice
    train_source = wash_n(read_csv(train_source_path))#[:2000]
  File "/remote-home/xtzhang/CTC/CTC2021/SpecialEdition/data/DatasetLoadingHelper.py", line 230, in wash_n
    return [re.sub("\n", "", i) for i in data ]
TypeError: 'NoneType' object is not iterable
